# Generated by Django 5.2.12 on 2026-04-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0134_owner"),
        ("ipam", "0086_gfk_indexes"),
        (
            "netbox_dns",
            "0030_dnsseckeytemplate_comments_dnsseckeytemplate_owner_and_more",
        ),
        ("tenancy", "0022_add_comments_to_organizationalmodel"),
        ("users", "0015_owner"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="record",
            index=models.Index(fields=["name"], name="netbox_dns_record_name"),
        ),
        migrations.AddIndex(
            model_name="record",
            index=models.Index(fields=["fqdn"], name="netbox_dns_record_fqdn"),
        ),
        migrations.AddIndex(
            model_name="record",
            index=models.Index(fields=["type"], name="netbox_dns_record_type"),
        ),
        migrations.AddIndex(
            model_name="record",
            index=models.Index(
                fields=["ip_address"], name="netbox_dns_record_ip_address"
            ),
        ),
        migrations.AddIndex(
            model_name="zone",
            index=models.Index(fields=["name"], name="netbox_dns_zone_name"),
        ),
        migrations.AddIndex(
            model_name="zone",
            index=models.Index(
                fields=["rfc2317_prefix"], name="netbox_dns_zone_rfc2317_prefix"
            ),
        ),
        migrations.AddIndex(
            model_name="zone",
            index=models.Index(
                fields=["arpa_network"], name="netbox_dns_zone_arpa_network"
            ),
        ),
    ]
